[package]
name = "meta-morph-pdf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf = "0.8.1"
printpdf = "0.6.0"
lopdf = "0.31.0"
